steps:
  # Install dependencies and build
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔨 Building Calendado with environment variables..."
        echo "Firebase API Key: ${_VITE_FIREBASE_API_KEY:0:10}..."
        echo "Firebase Project ID: ${_VITE_FIREBASE_PROJECT_ID}"
        
        # Install dependencies
        npm ci
        
        # Set environment variables and build
        export VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
        export VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
        export VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
        export VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}
        export VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}
        export VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
        export VITE_RECAPTCHA_SITE_KEY=${_VITE_RECAPTCHA_SITE_KEY}
        export VITE_APP_ENV=production
        export VITE_APP_BASE_URL=https://calendado.com
        export VITE_DEBUG_MODE=false
        
        # Build the project
        npm run build
        
        echo "✅ Build completed successfully"
        echo "📁 Build output:"
        ls -la dist/
    dir: '.'
  
  # Copy files to Firebase Hosting
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'storage'
      - 'cp'
      - '-r'
      - 'dist/*'
      - 'gs://calendado-prod.appspot.com/'
    dir: '.'

# Substitution variables (can be overridden in Firebase Console)
substitutions:
  _VITE_FIREBASE_API_KEY: 'AIzaSyB_6q5jQG1WywfsGpJ96VgmQfRSfsQ7T4k'
  _VITE_FIREBASE_AUTH_DOMAIN: 'calendado-prod.firebaseapp.com'
  _VITE_FIREBASE_PROJECT_ID: 'calendado-prod'
  _VITE_FIREBASE_STORAGE_BUCKET: 'calendado-prod.firebasestorage.app'
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '335629698770'
  _VITE_FIREBASE_APP_ID: '1:335629698770:web:935cd9c33c5b03ab354f0b'
  _VITE_RECAPTCHA_SITE_KEY: '6Le6nNArAAAAANxArJSBlIZ1kGrtQ03N8Z1BkI2K'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'